[config]
schemaVersion = "0.0.1"


[package]
namespace = "Jowday"
name = "Scyllaphonia"
versionNumber = "1.0.1"
description = "Removes the Scylla boss music."
websiteUrl = "https://github.com/The-Black-Lodge/JowdayScyllaphonia"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ENVY = "1.0.0"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-ModUtil = "3.1.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
